### ISSUE TITLE
JOSS Review: Paper questions

### ISSUE THREAD

**Issue by erexer** [swiss-seismological-service/DUGseis#11]
This is for the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6768).

- [x] Can you provide a source for the data used in Figure 2.
- [x] You mention that there are other programs used for seismic processing, can you give the names of those and cite them.

typos/grammar 

- [x] "Figure Figure 2 shows the layout..." says "Figure" twice
- [x] "Other commercial software for monitoring picoseismicity for structural health monitoring applications, e.g. in mines exists, but are only trigger-based" the commas in this sentence are incorrect, should be "Other commercial software for monitoring picoseismicity for structural health monitoring applications, e.g., in mines, exists but are only trigger-based".
- [x] "For large-scale experiments in underground laboratories (e.g., hydraulic stimulation, earthquake nucleation, nuclear waste disposal) continuous recordings of the seismicity data streams in MHz range are needed to study the rock response in great detail" should have a comma "For large-scale experiments in underground laboratories (e.g., hydraulic stimulation, earthquake nucleation, nuclear waste disposal), continuous recordings of the seismicity data streams in MHz range are needed to study the rock response in great detail"
- [x] "Since the software is python based, users can easily add their own processing routines." Python should be capitalized. 

I'd recommend running the paper through a grammar checker.

**Comment by mrosskopf** [comment]
Hi,
thank you for your suggestions. I adjusted the text and also ran it through a grammar checker again. 
I changed the event that was displayed in Figure 2. The one displayed now is just a few hours later, but the waveforms and channel information are already on zenodo. To open it in GUI, you can use the yaml file (just change the paths) and the sqlite file I now provided in the paper folder of the repository, plus the given waveform and channel information from zenodo. 
Are there any other suggestions to this topic? :)

**Comment by erexer** [comment]
Thanks! Could you add GMuG as a citation and make it clear in Figure 2 that the data comes from Rosskopf et al. 2024 (put it in the caption).

**Comment by mrosskopf** [comment]
Hi, I slightly changed the text to not include a citation in the summary section but I added the website of GMuG and of another software in the section "Statement of need" after slightly changing the text. The software itself do not have a direct citation, but I hope it is fine with the websites.
I also added the data citation in the caption.

**Comment by erexer** [comment]
You need a comma at the end of [this line](https://github.com/swiss-seismological-service/DUGseis/blob/main/paper/paper.bib#L13) so that the paper will render correctly :)

**Comment by mrosskopf** [comment]
Ah yes, of course! Sorry about that.

**Comment by erexer** [comment]
Thanks for bearing through this with me! There's still some grammar errors in the paper, for example, when I run the abstract through [this grammar checker](https://languagetool.org/), it points out:
- "detection of _the_ tiniest" should include "the"
- "(e.g._,_ hydraulic stimulation," should have a comma after e.g.
- "developed to manage, process_,_ and visualize continuous" may need an Oxford comma
- "software to experiment _with_ specific questions" requires a preposition

**Comment by mrosskopf** [comment]
I hope I corrected all errors now. I already used your suggested grammar checker in the past, but only the free version. I tried different ones again and hope they fix all the grammar mistakes.

**Comment by mrosskopf** [comment]
For your information - I just updated the paper again since it was now corrected by a professional proofreader.

**Comment by erexer** [comment]
Looks great!
