### ISSUE TITLE
JOSS Review: advice for example 

### ISSUE THREAD

**Issue by erexer** [swiss-seismological-service/DUGseis#14]
This is for the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6768), but isn't necessary for approval :)

The example has more steps than necessary to run out of the box. 

1. Ideally, you'd have a download command, `wget "<url>"`, so that users don't need to manually go to the site to download the example data. 

2. The [example dataset](https://dugseis.readthedocs.io/en/latest/example_dataset.html) has numerous steps to prepare the [download data](https://zenodo.org/records/10598393), it would be a much lower barrier of entry if you set up the example to run out of the box (organize the directory structure, create an empty cache dir, include an `.sqlite` file, edit the config file to work with the example data) so that all the user has to do is download the zip file, unzip the dir, `cd` into the dir, install the package, and run the `run_postProcessing_PaperExample.py` file.

**Comment by mrosskopf** [comment]
Hi, 
thanks for the suggestion! I added a new version to zenodo with a zip file, where your point 2 is taken care of and updated the documentation for it as well.
I need to have a better look at your first point. For now, I could not download the data via the terminal. 
Best

**Comment by erexer** [comment]
Great! I followed the updated instructions in the [Example Dataset](https://dugseis.readthedocs.io/en/latest/example_dataset.html) page and the command `dug-seis gui --operator="Your Name" --config=GUIExample_PaperExample.yaml` is failing for me with: 
```bash

Traceback (most recent call last):
  File "/<filepath>/DUGseis/.venv/lib/python3.11/site-packages/schema.py", line 483, in validate
    nvalue = Schema(
             ^^^^^^^
  File "/<filepath>/DUGseis/.venv/lib/python3.11/site-packages/schema.py", line 440, in validate
    return type(data)(o.validate(d, **kwargs) for d in data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<filepath>/DUGseis/.venv/lib/python3.11/site-packages/schema.py", line 440, in <genexpr>
    return type(data)(o.validate(d, **kwargs) for d in data)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/<filepath>/DUGseis/.venv/lib/python3.11/site-packages/schema.py", line 219, in validate
    raise SchemaError(
schema.SchemaError: Or(Use(<function _directory_exists at 0x12835cae0>)) did not validate 'C:/Users/Martina/Documents/PhD/workspace/BedrettoProcessingServer/DUGseis_RUNS/DUGseis_Paper/WAVEFORMS/continuous-04-bedretto'
_directory_exists('C:/Users/Martina/Documents/PhD/workspace/BedrettoProcessingServer/DUGseis_RUNS/DUGseis_Paper/WAVEFORMS/continuous-04-bedretto') raised ValueError("Directory 'C:/Users/Martina/Documents/PhD/workspace/BedrettoProcessingServer/DUGseis_RUNS/DUGseis_Paper/WAVEFORMS/continuous-04-bedretto' does not exist.")
```

it's also throwing
```bash
line 489, in validate
    raise SchemaError(
schema.SchemaError: Key 'paths' error:
Key 'asdf_folders' error:
Or(Use(<function _directory_exists at 0x12835cae0>)) did not validate 'C:/Users/Martina/Documents/PhD/workspace/BedrettoProcessingServer/DUGseis_RUNS/DUGseis_Paper/WAVEFORMS/continuous-04-bedretto'
_directory_exists('C:/Users/Martina/Documents/PhD/workspace/BedrettoProcessingServer/DUGseis_RUNS/DUGseis_Paper/WAVEFORMS/continuous-04-bedretto') raised ValueError("Directory 'C:/Users/Martina/Documents/PhD/workspace/BedrettoProcessingServer/DUGseis_RUNS/DUGseis_Paper/WAVEFORMS/continuous-04-bedretto' does not exist.")
```

**Comment by mrosskopf** [comment]
Thanks for pointing that out. For whatever reason, there was an old file within the folder with unchanged directories. I uploaded another new version, since I can not delete the old one.

**Comment by erexer** [comment]
Great, its working for me now.
