### ISSUE TITLE
improve first-time user experience with example dataset

### ISSUE THREAD

**Issue by trichter** [swiss-seismological-service/DUGseis#6]
Link to review issue: https://github.com/openjournals/joss-reviews/issues/6768

Hi!

As part of the JOSS review I tried to test DUGseis with the example dataset hosted at zenodo.

It would be nice if this example dataset was mentioned not only in the readme but also in the documentation.
I had to change the paths in the configuration file. Maybe these could be adapted in an update of the zenodo repository, or you could give instructions in the documenation.

After that, dugseis started without problems. But I have problems loading the waveforms. When the window opens, no waveforms are displayed.

![dugseisgui](https://github.com/swiss-seismological-service/DUGseis/assets/2046150/860ca892-095b-43fb-87e0-fb51d0bfcad9)

The error in the screenshot is because I clicked on "plot all traces", it has nothing to do with the above problem. However, the following warning might be relevant:

```
~/tmp/dugdata$ dug-seis gui --operator Tom --config post_processing_PaperExample.yaml
Creating/updating cache: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 902.18it/s]
/home/eule/.local/mambaforge/envs/dug_seis/lib/python3.11/site-packages/OpenGL/arrays/numpymodule.py:200: RuntimeWarning: overflow encountered in cast
  return numpy.ascontiguousarray( source, typeCode )
Creating/updating cache: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 51590.46it/s]

```

Any ideas?

**Comment by mrosskopf** [comment]
Hi! 

Thank you! Yes, it is a very good point to mention the example dataset in the documentation. I will add it in the following days and give instructions on what to change to use it. 

This was probably related to the pygtgraph version. I updated the version in the installation .toml file. Could you try and upgrade pyqtgraph with "pip install --upgrade pyqtgraph" and then rerun the dug-seis gui command? It should hopefully solve the issue. If it works the traces that you select should then display in the left black window and if you click on plot all traces a new window should open with all traces. 

Let me know if it works. :)

**Comment by trichter** [comment]
Thanks! With the updated documentation I got it working.
At first, I accidentally started the gui before running the processing script, which caused an error:

```
Traceback (most recent call last):
  File "/home/eule/dev/other/DUGseis/dug_seis/graphical_interface/main.py", line 1229, in on_channel_list_widget_itemSelectionChanged
    self._show_channels(selected_channels)
  File "/home/eule/dev/other/DUGseis/dug_seis/graphical_interface/main.py", line 456, in _show_channels
    plot = self.ui.plotWidget.addPlot(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eule/.local/mambaforge/envs/dug_seis/lib/python3.11/site-packages/pyqtgraph/graphicsItems/GraphicsLayout.py", line 71, in addPlot
    plot = PlotItem(**kargs)
           ^^^^^^^^^^^^^^^^^
  File "/home/eule/.local/mambaforge/envs/dug_seis/lib/python3.11/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 159, in __init__
    self.titleLabel = LabelItem('', size='11pt', parent=self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eule/.local/mambaforge/envs/dug_seis/lib/python3.11/site-packages/pyqtgraph/graphicsItems/LabelItem.py", line 20, in __init__
    GraphicsWidget.__init__(self, parent)
  File "/home/eule/.local/mambaforge/envs/dug_seis/lib/python3.11/site-packages/pyqtgraph/graphicsItems/GraphicsWidget.py", line 17, in __init__
    QtGui.QGraphicsWidget.__init__(self, *args, **kargs)
  File "/home/eule/.local/mambaforge/envs/dug_seis/lib/python3.11/site-packages/pyqtgraph/graphicsItems/GraphicsWidgetAnchor.py", line 21, in __init__
    self.geometryChanged.connect(self.__geometryChanged)
RuntimeError: '__init__' method of object's base class (LabelItem) not called.
```


I understand that the gui is only for refinement and this is properly described in the documentation. So no urgent need to fix this, but there could be a better error message.

When I run the python processing script from the example I see some lines like

```                                                              
Possible error
Possible error
Possible error
```

The `print("Possible error")` in `amplitude_based_magnitudes.py` looks like a debug leftover. Also the comment in line 91/92 does not describe what the code actually does. Please check.

After that I can start the gui and everything works fine.
